### ISSUE TITLE
when I use it with flask ,there is some error

### ISSUE THREAD

**Issue by QINMAN** [python-happybase/aiohappybase#7]
Here is my code of api view function:
 ```
async def async_check():
    async with pool.connection() as conn:
        buf = await conn.table('nMindPDF').cells(article.uuid, column='pdf')
    return buf
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
resp = loop.run_until_complete(async_check())
loop.close()
data = resp[0]
if not data:
    response = make_response()
else:
    response = make_response(data)
response.headers['Content-Type'] = 'application/pdf'
return response
```

the pool is defined like this:
```
import aiohappybase as happybase
pool = happybase.ConnectionPool(
    size=8,
    host=ip,
    port=port
)
```

But when I run it with `python manage.py runserver`, the first time is ok, and then, the error is like this:
```
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "E:\wa_projects\n-mind-api\apis\report\views.py", line 336, in get
    resp = loop.run_until_complete(async_check())
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\wa_projects\n-mind-api\apis\report\views.py", line 331, in async_check
    buf = await conn.table('nMindPDF').cells(article.uuid, column='pdf')
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohappybase\table.py", line 220, in cells
    cells = await self.client.getVer(
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\thriftpy2\contrib\aio\client.py", line 39, in _req
    yield from self._send(_api, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\thriftpy2\contrib\aio\client.py", line 52, in _send
    yield from self._oprot.trans.flush()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\thriftpy2\contrib\aio\transport\buffered.py", line 56, in flush
    self._trans.write(out)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\thriftpy2\contrib\aio\socket.py", line 193, in write
    self.writer.write(buff)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\streams.py", line 341, in write
    self._transport.write(data)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
```

Actually, I hope it can works with uwsgi. So would you help me? Thanks.

**Comment by aiudirog** [comment]
Before I dig into why the Windows `ProactorEventLoop` doesn't seem to be initialized properly, is there a particular reason you're using a non-async web framework like Flask instead of its async port Quart or something like FastAPI? You may have better luck using AIOHappybase in that environment.

Also, if you want a synchronous API, one is provided automatically through the `aiohappybase.sync` subpackage.

**Comment by aiudirog** [comment]
Hmm it looks like the event loop is closed for some reason, `_proactor` gets set to `None` when it closes: https://github.com/python/cpython/blob/3.9/Lib/asyncio/proactor_events.py#L686

**Comment by aiudirog** [comment]
@QINMAN Were you able to solve your problem or do you have any more information about it?

**Comment by aiudirog** [comment]
Actually, I missed that you are force creating a new event loop after creating the `ConnectionPool`. Internally, the async `ConnectionPool` in uses an `asyncio.LifoQueue` which is bound to the event loop it was created in. This is probably what is causing the issue.

I recommend you either use the `aiohappybase.sync` subpackage, the `happybase` proxy module for it, or an async web-framework instead.

I'm going to go ahead and close this issue for now. If none of  those solutions solve your problem, please reopen it with more information about how other solutions failed.
